=== RunedUniverse/r4m/r4m-build-executions-v1.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="https://api.runeduniverse.net/runes4tools/r4m-build-executions"
	xmlns="https://api.runeduniverse.net/runes4tools/r4m-build-executions"
	elementFormDefault="qualified">
	<xs:element name="executions" type="Model"></xs:element>
	<xs:complexType name="Model">
		<xs:sequence>
			<xs:element name="execution" type="Execution"
				minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="Execution">
		<xs:all>
			<xs:element name="profiles" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="profile" type="Profile"
							maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="lifecycles">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="lifecycle" type="Lifecycle"
							minOccurs="0" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:all>
		<xs:attribute name="id" type="xs:string" use="required" />
	</xs:complexType>

	<xs:complexType name="Profile">
		<xs:attribute name="id" type="xs:string" use="required" />
	</xs:complexType>

	<xs:complexType name="Lifecycle">
		<xs:all>
			<xs:element name="phases" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="phase" type="Phase" minOccurs="0"
							maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:all>
		<xs:attribute name="id" type="xs:string" use="required" />
	</xs:complexType>

	<xs:complexType name="Phase">
		<xs:all>
			<xs:element name="goals" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="goal" type="Goal" minOccurs="0"
							maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:all>
		<xs:attribute name="id" type="xs:string" use="required" />
	</xs:complexType>

	<xs:complexType name="Goal">
		<xs:all>
			<xs:element name="groupId" type="xs:string" />
			<xs:element name="artifactId" type="xs:string" />
			<xs:element name="fork" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="lifecycle" type="TragetLifecycle"
							minOccurs="0" maxOccurs="1" />
						<xs:element name="phases" minOccurs="0" maxOccurs="1">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="phase" type="TragetPhase"
										minOccurs="0" maxOccurs="unbounded" />
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:all>
		<xs:attribute name="id" type="xs:string" use="required" />
	</xs:complexType>

	<xs:complexType name="TragetLifecycle">
		<xs:all>
			<xs:element name="executions" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="execution" type="xs:string"
							minOccurs="0" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="startAtPhase" minOccurs="0" />
			<xs:element name="startFromPhase" minOccurs="0" />
			<xs:element name="excludePhases" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="phase" minOccurs="0"
							maxOccurs="unbounded">
							<xs:complexType>
								<xs:attribute name="id" type="xs:string"
									use="required" />
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:all>
		<xs:attribute name="id" type="xs:string" use="required" />
	</xs:complexType>

	<xs:complexType name="TragetPhase">
		<xs:all>
			<xs:element name="executions" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="execution" type="xs:string"
							minOccurs="0" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:all>
		<xs:attribute name="id" type="xs:string" use="required" />
	</xs:complexType>

</xs:schema>

=== RunedUniverse/r4m/build-executions.xml
<!-- <build xmlns="https://api.runeduniverse.net/runes4tools/r4m-build-executions" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://api.runeduniverse.net/runes4tools/r4m-build-executions 
	"> -->
<executions
	xmlns="https://api.runeduniverse.net/runes4tools/r4m-build-executions"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="https://api.runeduniverse.net/runes4tools/r4m-build-executions r4m-build-executions-v1.xsd">
	<execution id="default">
		<!-- <profiles> -->
		<!-- <profile id="default"></profile> -->
		<!-- <profile id="test"></profile> -->
		<!-- </profiles> -->
		<lifecycles>
			<lifecycle id="clean">
			</lifecycle>
			<lifecycle id="default">
				<phases>
					<phase id="compile">
						<goals>
							<goal id="build-invoker-summary">
								<groupId>net.runeduniverse.tools.runes4tools</groupId>
								<artifactId>runes4maven-maven-plugin</artifactId>
								<fork>
									<lifecycle id="builder">
										<executions>
											<execution>default</execution>
										</executions>
									</lifecycle>
								</fork>
							</goal>
						</goals>
					</phase>
					<phase id="test-compile">
						<goals>
							<goal id="build-invoker-summary">
								<groupId>net.runeduniverse.tools.runes4tools</groupId>
								<artifactId>runes4maven-maven-plugin</artifactId>
								<fork>
									<lifecycle id="builder">
										<executions>
											<execution>test</execution>
										</executions>
									</lifecycle>
								</fork>
							</goal>
						</goals>
					</phase>
				</phases>
			</lifecycle>
			<lifecycle id="site">
			</lifecycle>
		</lifecycles>
	</execution>
</executions>
