=== RunedUniverse/r4m/extension/src/main/resources/r4m-pem-v1.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="https://api.runeduniverse.net/runes4tools/r4m-pem"
	xmlns="https://api.runeduniverse.net/runes4tools/r4m-pem"
	elementFormDefault="qualified">
	<xs:element name="project-execution-model" type="Model" />
	<xs:complexType name="Model">
		<xs:all>
			<xs:element name="modelVersion" type="xs:string"
				default="1.0.0" />
			<xs:element name="executions">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="execution" type="Execution"
							minOccurs="0" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:all>
	</xs:complexType>

	<xs:complexType name="Execution">
		<xs:all>
			<xs:element name="triggers" minOccurs="0">
				<xs:complexType>
					<xs:choice>
						<xs:element name="always" minOccurs="0" maxOccurs="1" />
						<xs:element name="never" minOccurs="0" maxOccurs="1" />
						<xs:sequence>
							<xs:element name="default" minOccurs="0" maxOccurs="1">
								<xs:annotation>
									<xs:documentation>
										Execute when explicitly specified or no other
										Execution got explicitly specified via maven '@execution-id'.
									</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="on-call" minOccurs="0" maxOccurs="1">
								<xs:annotation>
									<xs:documentation>
										Execute when explicitly called by via maven
										'@execution-id'.
									</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:choice minOccurs="0" maxOccurs="unbounded">
								<xs:element name="active-profile" type="Profile">
									<xs:annotation>
										<xs:documentation>
											Trigger is successful when the Profile got
											explicitly mentioned
											by executing 'mvn -Pactive-profile'.
										</xs:documentation>
									</xs:annotation>
								</xs:element>
								<xs:element name="inactive-profile" type="Profile">
									<xs:annotation>
										<xs:documentation>
											Trigger is successful when the Profile was
											defined somewhere in the POM hierarchy and was not explicitly
											mentioned to maven.
										</xs:documentation>
									</xs:annotation>
								</xs:element>
								<xs:element name="provided-profile" type="Profile">
									<xs:annotation>
										<xs:documentation>
											Trigger is successful when the Profile was
											defined somewhere in the POM hierarchy.
										</xs:documentation>
									</xs:annotation>
								</xs:element>
								<xs:element name="missing-profile" type="Profile">
									<xs:annotation>
										<xs:documentation>
											Trigger is successful when the Profile was
											neither explicitly mentioned to maven nor defined somewhere
											in the POM hierarchy.
										</xs:documentation>
									</xs:annotation>
								</xs:element>
								<xs:element name="packaging-procedure"
									type="xs:string">
									<xs:annotation>
										<xs:documentation>
											Used to select packaging flag in POM. Keep
											in mind the POM's packaging flag only indirectly defines the
											Artifacts Type.
										</xs:documentation>
									</xs:annotation>
								</xs:element>
							</xs:choice>
						</xs:sequence>
					</xs:choice>
				</xs:complexType>
			</xs:element>
			<xs:element name="lifecycles" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="lifecycle" type="Lifecycle"
							minOccurs="0" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:all>
		<xs:attribute name="id" type="xs:string" use="required" />
		<xs:attribute name="source" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="override" />
					<xs:enumeration value="packaging" />
					<xs:enumeration value="plugin" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>

	<xs:complexType name="Profile">
		<xs:attribute name="id" type="xs:string" use="required" />
	</xs:complexType>

	<xs:complexType name="Lifecycle">
		<xs:all>
			<xs:element name="phases" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="phase" type="Phase" minOccurs="0"
							maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:all>
		<xs:attribute name="id" type="xs:string" use="required" />
	</xs:complexType>

	<xs:complexType name="Phase">
		<xs:all>
			<xs:element name="goals" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="goal" type="Goal" minOccurs="0"
							maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:all>
		<xs:attribute name="id" type="xs:string" use="required" />
	</xs:complexType>

	<xs:complexType name="Goal">
		<xs:all>
			<xs:element name="groupId" type="xs:string" />
			<xs:element name="artifactId" type="xs:string" />
			<xs:element name="fork" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="lifecycle" type="TragetLifecycle"
							minOccurs="0" maxOccurs="1" />
						<xs:element name="phases" minOccurs="0" maxOccurs="1">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="phase" type="TragetPhase"
										minOccurs="0" maxOccurs="unbounded" />
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="modes">
				<xs:complexType>
					<xs:sequence>
						<xs:choice minOccurs="1" maxOccurs="unbounded">
							<xs:element name="default" />
							<xs:element name="dev" />
							<xs:any />
						</xs:choice>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:all>
		<xs:attribute name="id" type="xs:string" use="required" />
	</xs:complexType>

	<xs:complexType name="TragetLifecycle">
		<xs:all>
			<xs:element name="executions" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="execution" type="xs:string"
							minOccurs="0" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="startAtPhase" minOccurs="0" />
			<xs:element name="stopAtPhase" minOccurs="0" />
			<xs:element name="excludePhases" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="phase" minOccurs="0"
							maxOccurs="unbounded">
							<xs:complexType>
								<xs:attribute name="id" type="xs:string"
									use="required" />
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:all>
		<xs:attribute name="id" type="xs:string" use="required" />
	</xs:complexType>

	<xs:complexType name="TragetPhase">
		<xs:all>
			<xs:element name="executions" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="execution" type="xs:string"
							minOccurs="0" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:all>
		<xs:attribute name="id" type="xs:string" use="required" />
	</xs:complexType>

</xs:schema>

=== RunedUniverse/r4m/extension/src/main/resources/pem.xml
<!-- <project-execution-model xmlns="https://api.runeduniverse.net/runes4tools/r4m-pem" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://api.runeduniverse.net/runes4tools/r4m-pem 
	https://api.runeduniverse.net/runes4tools/r4m-pem-v1.xsd"> -->
<project-execution-model
	xmlns="https://api.runeduniverse.net/runes4tools/r4m-pem"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="https://api.runeduniverse.net/runes4tools/r4m-pem r4m-pem-v1.xsd">

	<modelVersion>1.0.0</modelVersion>

	<executions>

		<execution id="default" source="override">
			<triggers>
				<always />
			</triggers>
			<lifecycles>
				<lifecycle id="default">
					<phases>
						<phase id="compile">
							<goals>
								<goal id="build-invoker-summary">
									<modes>
										<default />
										<dev />
									</modes>
									<groupId>net.runeduniverse.tools.maven.r4m</groupId>
									<artifactId>r4m-maven-extension</artifactId>
									<fork>
										<mode>default</mode>
										<executions>
											<execution id="default" />
										</executions>
										<lifecycle id="builder" />
									</fork>
								</goal>
							</goals>
						</phase>
						<phase id="test-compile">
							<goals>
								<goal id="build-invoker-summary">
									<modes>
										<default />
										<dev />
									</modes>
									<groupId>net.runeduniverse.tools.maven.r4m</groupId>
									<artifactId>r4m-maven-extension</artifactId>
									<fork>
										<mode>default</mode>
										<executions>
											<execution id="test" />
										</executions>
										<lifecycle id="builder" />
									</fork>
								</goal>
							</goals>
						</phase>
					</phases>
				</lifecycle>
			</lifecycles>
		</execution>
	</executions>
</project-execution-model>
